"""
Conversation memory for the AI operator chat.

The current chat is single-turn: every question is answered in isolation.
The user wants multi-turn cognition — "peki neden?" / "onu öne çıkar" /
"bunun için bir kampanya hazırla" — must resolve against the previous
turn's subject without the user repeating it.

This module owns:
    - chat_sessions: a session is a chat conversation. Many users / many
      sessions per user; a session_id is generated by the dashboard and
      stored in localStorage.
    - chat_turns: every (question, intent, primary_entity, response
      signature) tuple in chronological order.
    - resolve_follow_up(): detects short follow-up references ("neden",
      "peki", "onu", "bunu") and rewrites the question into a full
      stand-alone form using the previous turn's entity + intent.
    - anti_phrase_list(): returns the 5–8 sentences the synthesizer
      produced most recently in this session, so the LLM can be instructed
      to avoid repeating them.

This is in-process and SQLite-backed. No external service.
"""

from __future__ import annotations

import hashlib
import json
import re
import uuid
from dataclasses import dataclass
from typing import Any, Optional

from db import db_connection, execute_query, execute_write, now_iso


# ---------------------------------------------------------------------------
# Schema
# ---------------------------------------------------------------------------


def init_conversation_tables() -> None:
    with db_connection() as conn:
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS chat_sessions (
                id              TEXT PRIMARY KEY,
                user_id         INTEGER NOT NULL,
                opened_at       TEXT NOT NULL,
                last_turn_at    TEXT,
                active_entity_type TEXT,
                active_entity_id   INTEGER,
                active_entity_label TEXT,
                active_intent   TEXT,
                active_rule_id  INTEGER,
                active_rule_name TEXT,
                meta_json       TEXT
            )
            """
        )
        # In-place migration: alanları sonradan ekledik
        try:
            conn.execute("ALTER TABLE chat_sessions ADD COLUMN active_rule_id INTEGER")
        except Exception:
            pass
        try:
            conn.execute("ALTER TABLE chat_sessions ADD COLUMN active_rule_name TEXT")
        except Exception:
            pass
        conn.execute(
            "CREATE INDEX IF NOT EXISTS idx_sessions_user "
            "ON chat_sessions (user_id, last_turn_at DESC)"
        )
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS chat_turns (
                id              INTEGER PRIMARY KEY AUTOINCREMENT,
                session_id      TEXT NOT NULL,
                user_id         INTEGER NOT NULL,
                question        TEXT NOT NULL,
                resolved_question TEXT,
                intent          TEXT,
                routed_intent   TEXT,
                primary_entity_type TEXT,
                primary_entity_id   INTEGER,
                primary_entity_label TEXT,
                answer          TEXT,
                answer_signature TEXT,
                phrase_signatures_json TEXT,
                confidence      REAL,
                created_at      TEXT NOT NULL
            )
            """
        )
        conn.execute(
            "CREATE INDEX IF NOT EXISTS idx_turns_session "
            "ON chat_turns (session_id, id DESC)"
        )


init_conversation_tables()


# ---------------------------------------------------------------------------
# Session management
# ---------------------------------------------------------------------------


def open_session(user_id: int, session_id: str | None = None) -> dict:
    """Idempotent: returns the session row, creating it if needed."""
    sid = session_id or f"sess_{uuid.uuid4().hex[:16]}"
    row = execute_query(
        "SELECT * FROM chat_sessions WHERE id=? AND user_id=?",
        (sid, int(user_id)),
        one=True,
    )
    if row:
        return _row_to_session(row)

    ts = now_iso()
    execute_write(
        """
        INSERT INTO chat_sessions (
            id, user_id, opened_at, last_turn_at, meta_json
        )
        VALUES (?, ?, ?, NULL, '{}')
        """,
        (sid, int(user_id), ts),
    )
    return {
        "id": sid,
        "user_id": int(user_id),
        "opened_at": ts,
        "last_turn_at": None,
        "active_entity_type": None,
        "active_entity_id": None,
        "active_entity_label": None,
        "active_intent": None,
        "meta": {},
    }


def get_session(session_id: str) -> dict | None:
    row = execute_query(
        "SELECT * FROM chat_sessions WHERE id=?",
        (session_id,),
        one=True,
    )
    return _row_to_session(row) if row else None


def _row_to_session(row) -> dict:
    d = dict(row)
    raw = d.pop("meta_json", None) or "{}"
    try:
        d["meta"] = json.loads(raw)
    except json.JSONDecodeError:
        d["meta"] = {}
    return d


# ---------------------------------------------------------------------------
# Phrase signatures — anti-repetition fuel
# ---------------------------------------------------------------------------


_BOILERPLATE = {
    "şu", "şuan", "şu an", "anda", "bir", "ve", "ile", "için", "ama", "fakat",
    "olabilir", "görünüyor", "yapabilirim", "hazırlayabilirim",
    "küçük", "kısa", "iyi", "değerli",
}


def extract_phrase_signatures(text: str) -> list[str]:
    """Return short distinctive phrases (3..6 word windows) to forbid repeating.

    We don't grab the whole sentence — we grab the *opening* of each line and
    each bulleted recommendation. Those are the patterns that get noticed
    when a synthesizer repeats itself ("küçük bir indirim kampanyası" again
    and again, etc.).
    """
    if not text:
        return []
    sigs: list[str] = []
    for line in text.split("\n"):
        s = line.strip(" •-—*").strip()
        if not s:
            continue
        words = s.split()
        if len(words) < 3:
            continue
        # opening 3..6 words is the recognizable "tic"
        for window in (3, 4, 5):
            if len(words) >= window:
                opener = " ".join(words[:window]).lower()
                # filter out openers that are essentially boilerplate
                if sum(1 for w in opener.split() if w in _BOILERPLATE) >= window - 1:
                    continue
                sigs.append(opener)
                break
    # de-duplicate keeping order
    seen: set[str] = set()
    out: list[str] = []
    for s in sigs:
        if s not in seen:
            seen.add(s)
            out.append(s)
    return out


def answer_signature(text: str) -> str:
    """Stable hash for "have I said this answer recently" detection."""
    norm = re.sub(r"\s+", " ", (text or "").strip().lower())
    return hashlib.sha1(norm.encode("utf-8")).hexdigest()[:16]


# ---------------------------------------------------------------------------
# Turn recording
# ---------------------------------------------------------------------------


def record_turn(
    *,
    session_id: str,
    user_id: int,
    question: str,
    resolved_question: str | None,
    intent: str | None,
    routed_intent: str | None,
    primary_entity_type: str | None,
    primary_entity_id: int | None,
    primary_entity_label: str | None,
    answer: str,
    confidence: float | None,
) -> int:
    """Persist a turn and update session 'active' fields."""
    sigs = extract_phrase_signatures(answer)
    sig = answer_signature(answer)
    ts = now_iso()

    turn_id = execute_write(
        """
        INSERT INTO chat_turns (
            session_id, user_id, question, resolved_question,
            intent, routed_intent,
            primary_entity_type, primary_entity_id, primary_entity_label,
            answer, answer_signature, phrase_signatures_json,
            confidence, created_at
        )
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """,
        (
            session_id, int(user_id), question, resolved_question,
            intent, routed_intent,
            primary_entity_type, primary_entity_id, primary_entity_label,
            answer, sig, json.dumps(sigs),
            float(confidence) if confidence is not None else None,
            ts,
        ),
    )

    execute_write(
        """
        UPDATE chat_sessions
        SET last_turn_at=?,
            active_entity_type=COALESCE(?, active_entity_type),
            active_entity_id=COALESCE(?, active_entity_id),
            active_entity_label=COALESCE(?, active_entity_label),
            active_intent=COALESCE(?, active_intent)
        WHERE id=?
        """,
        (
            ts,
            primary_entity_type,
            primary_entity_id,
            primary_entity_label,
            routed_intent or intent,
            session_id,
        ),
    )
    return turn_id


def set_active_rule(session_id: str, rule_id: int | None, rule_name: str | None = None) -> None:
    """Conversational rule edit için session'ın "aktif kuralını" işaretle.

    Operatör "bu kuralı kapat" dediğinde rule_edit modülü session'dan
    bu rule_id'yi alıp işlem yapar.
    """
    if not session_id:
        return
    try:
        execute_write(
            """
            UPDATE chat_sessions
            SET active_rule_id=?, active_rule_name=?
            WHERE id=?
            """,
            (int(rule_id) if rule_id else None, rule_name, session_id),
        )
    except Exception as exc:
        print(f"[CONV_MEMORY] set_active_rule failed: {exc}")


def get_active_rule(session_id: str) -> tuple[int | None, str | None]:
    """Session'ın aktif rule_id ve name'ini döndürür (yoksa None, None)."""
    if not session_id:
        return None, None
    row = execute_query(
        "SELECT active_rule_id, active_rule_name FROM chat_sessions WHERE id=?",
        (session_id,), one=True,
    )
    if not row:
        return None, None
    return (
        int(row["active_rule_id"]) if row["active_rule_id"] is not None else None,
        row["active_rule_name"],
    )


def recent_turns(session_id: str, limit: int = 6) -> list[dict]:
    rows = execute_query(
        """
        SELECT * FROM chat_turns
        WHERE session_id=?
        ORDER BY id DESC LIMIT ?
        """,
        (session_id, int(limit)),
    )
    out = []
    for r in rows:
        d = dict(r)
        try:
            d["phrase_signatures"] = json.loads(d.pop("phrase_signatures_json", "[]") or "[]")
        except json.JSONDecodeError:
            d["phrase_signatures"] = []
        out.append(d)
    return list(reversed(out))


def anti_phrase_list(session_id: str, limit_turns: int = 4) -> list[str]:
    """Phrases the LLM should avoid repeating in the next turn."""
    turns = recent_turns(session_id, limit=limit_turns)
    phrases: list[str] = []
    seen: set[str] = set()
    for t in turns:
        for p in t.get("phrase_signatures") or []:
            if p not in seen:
                seen.add(p)
                phrases.append(p)
    return phrases[:12]


# ---------------------------------------------------------------------------
# Follow-up resolution
# ---------------------------------------------------------------------------


# Short fragments that mean "continue with the previous subject".
_FOLLOWUP_HINTS = (
    "peki",        # peki neden? / peki nasıl?
    "neden",       # neden? (standalone)
    "niye",
    "nasıl",
    "ya da",
    "onu",
    "bunu",
    "bu ürün",
    "bu kampanya",
    "öne çıkar",
    "öne çıkaralım",
    "kampanya hazırla",
    "bir fikir",
    "fikir üret",
    "bir öneri",
    "anlat",
    "açıkla",
    "detay",
    "devam",
    "tekrar",
)


_QUESTION_WORD_RE = re.compile(
    r"\b(ürün|product|kampanya|campaign|mağaza|store|sipariş|order|"
    r"yorum|review|stok|stock|satış|sales|müşteri|customer)\b",
    re.IGNORECASE,
)


def _looks_like_followup(question: str) -> bool:
    q = (question or "").strip().lower()
    if not q:
        return False
    # Standalone subject already in question → not a follow-up
    if _QUESTION_WORD_RE.search(q):
        # Unless it's *just* "bu ürün için" + something short
        if not q.startswith(("bu ürün", "bu kampanya", "o ürün", "şu ürün")):
            return False
    # Heuristic: short question (≤ 6 words) or starts with a follow-up hint
    word_count = len(q.split())
    if word_count <= 4:
        return True
    if any(q.startswith(hint) for hint in _FOLLOWUP_HINTS):
        return True
    if any(q == hint or q == hint + "?" for hint in _FOLLOWUP_HINTS):
        return True
    return False


@dataclass
class FollowUpResolution:
    is_followup: bool
    resolved_question: str        # the question to feed to retrieval
    inherited_entity_label: str | None
    inherited_intent: str | None
    rationale: str                # for logging / dashboard chip


def resolve_follow_up(question: str, session_id: str) -> FollowUpResolution:
    """If the question looks like a follow-up, rewrite it using session state."""
    if not session_id:
        return FollowUpResolution(False, question, None, None, "no_session")

    session = get_session(session_id)
    if not session or not session.get("last_turn_at"):
        return FollowUpResolution(False, question, None, None, "fresh_session")

    if not _looks_like_followup(question):
        return FollowUpResolution(False, question, None, None, "standalone_question")

    active_label = session.get("active_entity_label")
    active_intent = session.get("active_intent")
    if not active_label and not active_intent:
        return FollowUpResolution(False, question, None, None, "no_active_context")

    q = (question or "").strip().rstrip("?")

    # "neden" / "peki neden" → "why" lookup for the active subject
    if q in ("neden", "peki", "peki neden") or q.startswith(("peki neden", "neden ")):
        if active_intent and "sales" in active_intent.lower():
            rewritten = "Satışlar neden bu durumda?"
        elif active_label:
            rewritten = f"{active_label} için durumun arkasındaki sebepler ne?"
        else:
            rewritten = "Bunun arkasındaki sebepler ne?"
        return FollowUpResolution(
            True, rewritten, active_label, active_intent,
            f"why_lookup({active_intent or '-'})",
        )

    # "onu öne çıkaralım" / "kampanya hazırla" → action proposal for active entity
    if any(k in q for k in ("öne çıkar", "kampanya hazırla", "instagram", "tanıt", "duyur")):
        if active_label:
            rewritten = f"{active_label} için yeni bir kampanya akışı önerebilir misin?"
        else:
            rewritten = "Aktif konu için bir kampanya akışı önerir misin?"
        return FollowUpResolution(
            True, rewritten, active_label, "growth_marketing",
            f"action_proposal({active_label or '-'})",
        )

    # "bir fikir üret" / "bir öneri" → generic recommendation around active entity
    if any(k in q for k in ("fikir", "öneri")):
        if active_label:
            rewritten = f"{active_label} için strateji önerisi"
        else:
            rewritten = "Mevcut bağlam için strateji önerisi"
        return FollowUpResolution(
            True, rewritten, active_label, "insights",
            f"recommend_around({active_label or '-'})",
        )

    # generic "anlat / açıkla / detay" → describe the active subject
    if any(k in q for k in ("anlat", "açıkla", "detay", "daha fazla")):
        if active_label:
            rewritten = f"{active_label} hakkında biraz daha detay"
        else:
            rewritten = "Bu konu hakkında daha fazla bilgi"
        return FollowUpResolution(
            True, rewritten, active_label, active_intent,
            f"elaborate({active_label or '-'})",
        )

    # Default: append the active entity to the short question
    if active_label and active_label.lower() not in q:
        rewritten = f"{question.strip()} ({active_label})"
        return FollowUpResolution(
            True, rewritten, active_label, active_intent,
            f"append_entity({active_label})",
        )

    return FollowUpResolution(False, question, None, None, "no_rewrite_path")


# ---------------------------------------------------------------------------
# Context bundle for the synthesizer
# ---------------------------------------------------------------------------


def conversation_context(session_id: str, limit_turns: int = 4) -> dict:
    """Lightweight summary for the synthesizer prompt."""
    session = get_session(session_id) or {}
    turns = recent_turns(session_id, limit=limit_turns)
    return {
        "session_id": session_id,
        "active_entity_label": session.get("active_entity_label"),
        "active_entity_type": session.get("active_entity_type"),
        "active_intent": session.get("active_intent"),
        "history": [
            {
                "question": t.get("question"),
                "resolved_question": t.get("resolved_question"),
                "intent": t.get("routed_intent") or t.get("intent"),
                "entity": t.get("primary_entity_label"),
            }
            for t in turns
        ],
        "anti_phrases": anti_phrase_list(session_id),
    }
